# 
# can_has_chat config
#
#
development:
  # Process ID file - used for controlling the daemonized chat server process
  pid_file: "tmp/development.chat_server.pid"
  # Socket to connect to chat_server on
  socket: "drbunix://tmp/development.chat_server.sock"
  # Total number of connections to the jabber server to maintain
  # New connections will "bump" the oldest out of the list
  max_connections: 10
  # Number of seconds to wait before "reaping" a chat connection
  chat_timeout: 60
  # The IP address/domain name of your Jabber server
  jabber_server: "talk.localhost"
  # The "realm" or "domain" that your Jabber users belong in
  # For example:  imauser@my_jabber_realm is the Jabber nick, then
  # my_jabber_realm is jabber_realm.
  jabber_realm: "talk.localhost"
  # whether or not to try connecting to the Jabber server anonymously
  use_anonymous_jabber: false
  # where to log chat_server output
  log_file: "log/development.chat_server.log"
  # log level of output
  log_level: "debug"
  # if you're using the custom mongrel http handler, then how long
  # the "push" connections will remain alive.  if a connection dies
  # by reaching this limit, the client should initiate a new connection
  mongrel_keepalive: 30

production_local:
    # Process ID file - used for controlling the daemonized chat server process
    pid_file: "tmp/production_local.chat_server.pid"
    # Socket to connect to chat_server on
    socket: "drbunix://tmp/production_local.chat_server.sock"
    # Total number of connections to the jabber server to maintain
    # New connections will "bump" the oldest out of the list
    max_connections: 10
    # Number of seconds to wait before "reaping" a chat connection
    chat_timeout: 300
    # The IP address/domain name of your Jabber server
    jabber_server: "devlocal.7.am"
    # The "realm" or "domain" that your Jabber users belong in
    # For example:  imauser@my_jabber_realm is the Jabber nick, then
    # my_jabber_realm is jabber_realm.
    jabber_realm: "devlocal.7.am"
    # whether or not to try connecting to the Jabber server anonymously
    use_anonymous_jabber: false
    # where to log chat_server output
    log_file: "log/production_local.chat_server.log"
    # log level of output
    log_level: "debug"
    # if you're using the custom mongrel http handler, then how long
    # the "push" connections will remain alive.  if a connection dies
    # by reaching this limit, the client should initiate a new connection
    mongrel_keepalive: 30

test:
    # Process ID file - used for controlling the daemonized chat server process
    pid_file: "tmp/test.chat_server.pid"
    # Socket to connect to chat_server on
    socket: "drbunix://tmp/test.chat_server.sock"
    # Total number of connections to the jabber server to maintain
    # New connections will "bump" the oldest out of the list
    max_connections: 10
    # Number of seconds to wait before "reaping" a chat connection
    chat_timeout: 60
    # The IP address/domain name of your Jabber server
    jabber_server: "talklocal.7.am"
    # The "realm" or "domain" that your Jabber users belong in
    # For example:  imauser@my_jabber_realm is the Jabber nick, then
    # my_jabber_realm is jabber_realm.
    jabber_realm: "talk.7.am"
    # whether or not to try connecting to the Jabber server anonymously
    use_anonymous_jabber: true
    # where to log chat_server output
    log_file: "log/development.chat_server.log"
    # log level of output
    log_level: "info"
    # if you're using the custom mongrel http handler, then how long
    # the "push" connections will remain alive.  if a connection dies
    # by reaching this limit, the client should initiate a new connection
    mongrel_keepalive: 30

production:
    # Process ID file - used for controlling the daemonized chat server process
    pid_file: "tmp/production.chat_server.pid"
    # Socket to connect to chat_server on
    socket: "drbunix://tmp/production.chat_server.sock"
    # Total number of connections to the jabber server to maintain
    # New connections will "bump" the oldest out of the list
    max_connections: 10
    # Number of seconds to wait before "reaping" a chat connection
    chat_timeout: 60
    # The IP address/domain name of your Jabber server
    jabber_server: "talk.beta.7.am"
    # The "realm" or "domain" that your Jabber users belong in
    # For example:  imauser@my_jabber_realm is the Jabber nick, then
    # my_jabber_realm is jabber_realm.
    jabber_realm: "talk.7.am"
    # whether or not to try connecting to the Jabber server anonymously
    use_anonymous_jabber: false
    # where to log chat_server output
    log_file: "log/production.chat_server.log"
    # log level of output
    log_level: "info"
    # if you're using the custom mongrel http handler, then how long
    # the "push" connections will remain alive.  if a connection dies
    # by reaching this limit, the client should initiate a new connection
    mongrel_keepalive: 30
