# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

development: &defaults
  application_id: 122333724496228
  api_key: 935d609b1bdccb37f511dbd63a6d103d
  secret_key: 7ba57d81ddbadb50009301d303ed9c03
  canvas_page_name: devseven
  callback_url:
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000

staging:
  <<: *defaults
    
test:
  api_key: 
  secret_key: 
  canvas_page_name: 
  callback_url:
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000

production:
  api_key: 1f5bc2287b6744a819a81104c544c74a
  secret_key: b9447108e39e6204418daf9dd8f159be
  canvas_page_name: synclocateconnect
  callback_url: 
  pretty_errors: true
  set_asset_host_to_callback_url: true   
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000

reporting:
  application_id: 122333724496228
  api_key: 935d609b1bdccb37f511dbd63a6d103d
  secret_key: 7ba57d81ddbadb50009301d303ed9c03
  canvas_page_name: devseven
  callback_url:
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000

