development: &defaults
  pid_file: social_daemon.pid
  log_file: social_daemon.log
  work_interval: 10

staging:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  work_interval: 900

